language: node_js
node_js:
  - "7"
before_script :
 - "npm install -g mocha"
script:
 - "npm test"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project devpipeline-staging --token $FIREBASE_TOKEN﻿